apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenexai-backend
  labels:
    app: tenexai-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenexai-backend
  template:
    metadata:
      labels:
        app: tenexai-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/YOUR_PROJECT_ID/tenexai-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tenexai-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tenexai-secrets
              key: JWT_SECRET
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tenexai-secrets
              key: GEMINI_API_KEY
        - name: BCRYPT_ROUNDS
          value: "12"
        - name: UPLOAD_DIR
          value: "./uploads"
        - name: MAX_FILE_SIZE
          value: "10485760"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tenexai-backend-service
spec:
  selector:
    app: tenexai-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 